// Minimal citation shape shared by the app (snake_case) and the demo
// (camelCase) — only the fields the export needs, so both can call this.
export interface ExportCitation {
  marker: number;
  source: string;
  chunk_index?: number;
  chunkIndex?: number;
  score: number;
  snippet: string;
}

// Render a Q&A turn as a self-contained Markdown document: the question, the
// answer (markers intact), and a numbered Sources section. Lets a user save or
// paste a cited answer straight into notes/issues/docs.
export function answerToMarkdown(
  question: string,
  answer: string,
  citations: ExportCitation[],
  meta: { mode: string; model: string },
): string {
  const lines: string[] = [];
  lines.push(`# ${question.trim()}`, "");
  lines.push(answer.trim(), "");
  if (citations.length) {
    lines.push("## Sources", "");
    for (const c of citations) {
      const chunk = c.chunk_index ?? c.chunkIndex ?? 0;
      lines.push(
        `${c.marker}. **${c.source}** (chunk ${chunk}, score ${c.score.toFixed(3)})`,
      );
      lines.push(`   > ${c.snippet}`);
    }
    lines.push("");
  }
  const via =
    meta.mode === "ollama" ? `generated by ${meta.model || "ollama"}` : "extractive answer";
  lines.push("---", `_Answered by localrag (${via})._`);
  return lines.join("\n");
}

// Trigger a client-side download of a text file (no backend involved).
export function downloadText(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
